In [ ]:
import pandas as pd
----import numpy as np
impo.0.00.01rt warnings
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings('ignore')

y = [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4]
x1 = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10,]
x2 = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68]
x3 = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8]
x4 = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]

data_dict= {'y':y, 'x1' : x1, 'x2' : x2, 'x3' : x3, 'x4' : x4,}

print(data_dict)
print()

df = pd.DataFrame(data_dict)
print(df)
print()

df['y'] = 1

print(df)
print()

x= df

trans_x = x.T
print(trans_x)
print()

multi_x = np.dot(trans_x, x)
multi_x

print(multi_x)
print()

inv_multi_x = np.linalg.inv(multi_x)
inv_multi_x

print(inv_multi_x)
print()

b= np.dot(inv_multi_x, trans_x)
b

beta = np.dot(b, y)
beta

beta_df = pd.DataFrame(beta)
print(beta_df)

{'y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4], 'x1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10], 'x2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68], 'x3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8], 'x4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}

        y  x1  x2  x3  x4
0    78.5   7  26   6  60
1    74.3   1  29  15  52
2   104.3  11  56   8  20
3    87.6  11  31   8  47
4    95.9   7  52   6  33
5   109.2  11  55   9  22
6   102.7   3  71  17   6
7    72.5   1  31  22  44
8    93.1   2  54  18  22
9   115.9  21  47   4  26
10   83.8   1  40  23  34
11  113.3  11  66   9  12
12  109.4  10  68   8  12

    y  x1  x2  x3  x4
0   1   7  26   6  60
1   1   1  29  15  52
2   1  11  56   8  20
3   1  11  31   8  47
4   1   7  52   6  33
5   1  11  55   9  22
6   1   3  71  17   6
7   1   1  31  22  44
8   1   2  54  18  22
9   1  21  47   4  26
10  1   1  40  23  34
11  1  11  66   9  12
12  1  10  68   8  12

    0   1   2   3   4   5   6   7   8   9   10  11  12
y    1   1   1   1   1   1   1   1   1   1   1   1   1
x1   7   1  11  11   7  11   3   1   2  21   1  11  10
x2  26  29  56  31  52  55  71  31  54  47  40  66  68
x3   6  15   8   8   6   9  17  22  18   4  23   9   8
x4  60  52  20  47  33  22   6  44  22  26  34  12  12

[[   13    97   626   153   390]
 [   97  1139  4922   769  2620]
 [  626  4922 33050  7201 15739]
 [  153   769  7201  2293  4628]
 [  390  2620 15739  4628 15062]]

[[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]

           0
0  62.405369
1   1.551103
2   0.510168
3   0.101909
4  -0.144061